spring:
  application:
    name: jyblog
  thymeleaf:
    cache: false
    mode: HTML
  profiles:
    active: dev

comment.avatar: /images/avatar.png
# 启动之后要打开的地址
open:
  browser:
    url: http://localhost:8080
    openUrl: false


